<?php

function cptui_register_my_cpts() {

	/**
	 * Post Type: Documents.
	 */

	$labels = [
		"name" => esc_html__( "Documents", "selskaberne" ),
		"singular_name" => esc_html__( "Document", "selskaberne" ),
		"menu_name" => esc_html__( "Documents", "selskaberne" ),
		"all_items" => esc_html__( "All Documents", "selskaberne" ),
		"add_new" => esc_html__( "Add new", "selskaberne" ),
		"add_new_item" => esc_html__( "Add new Document", "selskaberne" ),
		"edit_item" => esc_html__( "Edit Document", "selskaberne" ),
		"new_item" => esc_html__( "New Document", "selskaberne" ),
		"view_item" => esc_html__( "View Document", "selskaberne" ),
		"view_items" => esc_html__( "View Documents", "selskaberne" ),
		"search_items" => esc_html__( "Search Documents", "selskaberne" ),
		"not_found" => esc_html__( "No Documents found", "selskaberne" ),
		"not_found_in_trash" => esc_html__( "No Documents found in trash", "selskaberne" ),
		"parent" => esc_html__( "Parent Document:", "selskaberne" ),
		"featured_image" => esc_html__( "Featured image for this Document", "selskaberne" ),
		"set_featured_image" => esc_html__( "Set featured image for this Document", "selskaberne" ),
		"remove_featured_image" => esc_html__( "Remove featured image for this Document", "selskaberne" ),
		"use_featured_image" => esc_html__( "Use as featured image for this Document", "selskaberne" ),
		"archives" => esc_html__( "Document archives", "selskaberne" ),
		"insert_into_item" => esc_html__( "Insert into Document", "selskaberne" ),
		"uploaded_to_this_item" => esc_html__( "Upload to this Document", "selskaberne" ),
		"filter_items_list" => esc_html__( "Filter Documents list", "selskaberne" ),
		"items_list_navigation" => esc_html__( "Documents list navigation", "selskaberne" ),
		"items_list" => esc_html__( "Documents list", "selskaberne" ),
		"attributes" => esc_html__( "Documents attributes", "selskaberne" ),
		"name_admin_bar" => esc_html__( "Document", "selskaberne" ),
		"item_published" => esc_html__( "Document published", "selskaberne" ),
		"item_published_privately" => esc_html__( "Document published privately.", "selskaberne" ),
		"item_reverted_to_draft" => esc_html__( "Document reverted to draft.", "selskaberne" ),
		"item_trashed" => esc_html__( "Document trashed.", "selskaberne" ),
		"item_scheduled" => esc_html__( "Document scheduled", "selskaberne" ),
		"item_updated" => esc_html__( "Document updated.", "selskaberne" ),
		"parent_item_colon" => esc_html__( "Parent Document:", "selskaberne" ),
	];

	$args = [
		"label" => esc_html__( "Documents", "selskaberne" ),
		"labels" => $labels,
		"description" => "",
		"public" => true,
		"publicly_queryable" => true,
		"show_ui" => true,
		"show_in_rest" => true,
		"rest_base" => "",
		"rest_controller_class" => "WP_REST_Posts_Controller",
		"rest_namespace" => "wp/v2",
		"has_archive" => false,
		"show_in_menu" => true,
		"show_in_nav_menus" => true,
		"delete_with_user" => false,
		"exclude_from_search" => false,
		"capability_type" => "post",
		"map_meta_cap" => true,
		"hierarchical" => false,
		"can_export" => false,
		"rewrite" => [ "slug" => "document", "with_front" => true ],
		"query_var" => true,
		"menu_position" => 100,
		"menu_icon" => "dashicons-media-document",
		"supports" => [ "title", "editor", "thumbnail", "custom-fields" ],
		"taxonomies" => [ "media_category" ],
		"show_in_graphql" => false,
	];

	register_post_type( "document", $args );

	/**
	 * Post Type: Images.
	 */

	$labels = [
		"name" => esc_html__( "Images", "selskaberne" ),
		"singular_name" => esc_html__( "Image", "selskaberne" ),
		"menu_name" => esc_html__( "Images", "selskaberne" ),
		"all_items" => esc_html__( "All Images", "selskaberne" ),
		"add_new" => esc_html__( "Add new", "selskaberne" ),
		"add_new_item" => esc_html__( "Add new Image", "selskaberne" ),
		"edit_item" => esc_html__( "Edit Image", "selskaberne" ),
		"new_item" => esc_html__( "New Image", "selskaberne" ),
		"view_item" => esc_html__( "View Image", "selskaberne" ),
		"view_items" => esc_html__( "View Images", "selskaberne" ),
		"search_items" => esc_html__( "Search Images", "selskaberne" ),
		"not_found" => esc_html__( "No Images found", "selskaberne" ),
		"not_found_in_trash" => esc_html__( "No Images found in trash", "selskaberne" ),
		"parent" => esc_html__( "Parent Image:", "selskaberne" ),
		"featured_image" => esc_html__( "Featured image for this Image", "selskaberne" ),
		"set_featured_image" => esc_html__( "Set featured image for this Image", "selskaberne" ),
		"remove_featured_image" => esc_html__( "Remove featured image for this Image", "selskaberne" ),
		"use_featured_image" => esc_html__( "Use as featured image for this Image", "selskaberne" ),
		"archives" => esc_html__( "Image archives", "selskaberne" ),
		"insert_into_item" => esc_html__( "Insert into Image", "selskaberne" ),
		"uploaded_to_this_item" => esc_html__( "Upload to this Image", "selskaberne" ),
		"filter_items_list" => esc_html__( "Filter Images list", "selskaberne" ),
		"items_list_navigation" => esc_html__( "Images list navigation", "selskaberne" ),
		"items_list" => esc_html__( "Images list", "selskaberne" ),
		"attributes" => esc_html__( "Images attributes", "selskaberne" ),
		"name_admin_bar" => esc_html__( "Image", "selskaberne" ),
		"item_published" => esc_html__( "Image published", "selskaberne" ),
		"item_published_privately" => esc_html__( "Image published privately.", "selskaberne" ),
		"item_reverted_to_draft" => esc_html__( "Image reverted to draft.", "selskaberne" ),
		"item_trashed" => esc_html__( "Image trashed.", "selskaberne" ),
		"item_scheduled" => esc_html__( "Image scheduled", "selskaberne" ),
		"item_updated" => esc_html__( "Image updated.", "selskaberne" ),
		"parent_item_colon" => esc_html__( "Parent Image:", "selskaberne" ),
	];

	$args = [
		"label" => esc_html__( "Images", "selskaberne" ),
		"labels" => $labels,
		"description" => "",
		"public" => true,
		"publicly_queryable" => true,
		"show_ui" => true,
		"show_in_rest" => true,
		"rest_base" => "",
		"rest_controller_class" => "WP_REST_Posts_Controller",
		"rest_namespace" => "wp/v2",
		"has_archive" => false,
		"show_in_menu" => true,
		"show_in_nav_menus" => true,
		"delete_with_user" => false,
		"exclude_from_search" => false,
		"capability_type" => "post",
		"map_meta_cap" => true,
		"hierarchical" => false,
		"can_export" => false,
		"rewrite" => [ "slug" => "image", "with_front" => true ],
		"query_var" => true,
		"menu_position" => 100,
		"menu_icon" => "dashicons-format-image",
		"supports" => [ "title", "editor", "thumbnail", "custom-fields" ],
		"taxonomies" => [ "media_category" ],
		"show_in_graphql" => false,
	];

	register_post_type( "image", $args );

	/**
	 * Post Type: Videos.
	 */

	$labels = [
		"name" => esc_html__( "Videos", "selskaberne" ),
		"singular_name" => esc_html__( "Video", "selskaberne" ),
		"menu_name" => esc_html__( "Videos", "selskaberne" ),
		"all_items" => esc_html__( "All Videos", "selskaberne" ),
		"add_new" => esc_html__( "Add new", "selskaberne" ),
		"add_new_item" => esc_html__( "Add new Video", "selskaberne" ),
		"edit_item" => esc_html__( "Edit Video", "selskaberne" ),
		"new_item" => esc_html__( "New Video", "selskaberne" ),
		"view_item" => esc_html__( "View Video", "selskaberne" ),
		"view_items" => esc_html__( "View Videos", "selskaberne" ),
		"search_items" => esc_html__( "Search Videos", "selskaberne" ),
		"not_found" => esc_html__( "No Videos found", "selskaberne" ),
		"not_found_in_trash" => esc_html__( "No Videos found in trash", "selskaberne" ),
		"parent" => esc_html__( "Parent Video:", "selskaberne" ),
		"featured_image" => esc_html__( "Featured image for this Video", "selskaberne" ),
		"set_featured_image" => esc_html__( "Set featured image for this Video", "selskaberne" ),
		"remove_featured_image" => esc_html__( "Remove featured image for this Video", "selskaberne" ),
		"use_featured_image" => esc_html__( "Use as featured image for this Video", "selskaberne" ),
		"archives" => esc_html__( "Video archives", "selskaberne" ),
		"insert_into_item" => esc_html__( "Insert into Video", "selskaberne" ),
		"uploaded_to_this_item" => esc_html__( "Upload to this Video", "selskaberne" ),
		"filter_items_list" => esc_html__( "Filter Videos list", "selskaberne" ),
		"items_list_navigation" => esc_html__( "Videos list navigation", "selskaberne" ),
		"items_list" => esc_html__( "Videos list", "selskaberne" ),
		"attributes" => esc_html__( "Videos attributes", "selskaberne" ),
		"name_admin_bar" => esc_html__( "Video", "selskaberne" ),
		"item_published" => esc_html__( "Video published", "selskaberne" ),
		"item_published_privately" => esc_html__( "Video published privately.", "selskaberne" ),
		"item_reverted_to_draft" => esc_html__( "Video reverted to draft.", "selskaberne" ),
		"item_trashed" => esc_html__( "Video trashed.", "selskaberne" ),
		"item_scheduled" => esc_html__( "Video scheduled", "selskaberne" ),
		"item_updated" => esc_html__( "Video updated.", "selskaberne" ),
		"parent_item_colon" => esc_html__( "Parent Video:", "selskaberne" ),
	];

	$args = [
		"label" => esc_html__( "Videos", "selskaberne" ),
		"labels" => $labels,
		"description" => "",
		"public" => true,
		"publicly_queryable" => true,
		"show_ui" => true,
		"show_in_rest" => true,
		"rest_base" => "",
		"rest_controller_class" => "WP_REST_Posts_Controller",
		"rest_namespace" => "wp/v2",
		"has_archive" => false,
		"show_in_menu" => true,
		"show_in_nav_menus" => true,
		"delete_with_user" => false,
		"exclude_from_search" => false,
		"capability_type" => "post",
		"map_meta_cap" => true,
		"hierarchical" => false,
		"can_export" => false,
		"rewrite" => [ "slug" => "video", "with_front" => true ],
		"query_var" => true,
		"menu_position" => 100,
		"menu_icon" => "dashicons-editor-video",
		"supports" => [ "title", "editor", "thumbnail", "custom-fields" ],
		"taxonomies" => [ "media_category" ],
		"show_in_graphql" => false,
	];

	register_post_type( "video", $args );

	/**
	 * Post Type: Vectors.
	 */

	$labels = [
		"name" => esc_html__( "Vectors", "selskaberne" ),
		"singular_name" => esc_html__( "Vector", "selskaberne" ),
		"menu_name" => esc_html__( "Vectors", "selskaberne" ),
		"all_items" => esc_html__( "All Vectors", "selskaberne" ),
		"add_new" => esc_html__( "Add new", "selskaberne" ),
		"add_new_item" => esc_html__( "Add new Vector", "selskaberne" ),
		"edit_item" => esc_html__( "Edit Vector", "selskaberne" ),
		"new_item" => esc_html__( "New Vector", "selskaberne" ),
		"view_item" => esc_html__( "View Vector", "selskaberne" ),
		"view_items" => esc_html__( "View Vectors", "selskaberne" ),
		"search_items" => esc_html__( "Search Vectors", "selskaberne" ),
		"not_found" => esc_html__( "No Vectors found", "selskaberne" ),
		"not_found_in_trash" => esc_html__( "No Vectors found in trash", "selskaberne" ),
		"parent" => esc_html__( "Parent Vector:", "selskaberne" ),
		"featured_image" => esc_html__( "Featured image for this Vector", "selskaberne" ),
		"set_featured_image" => esc_html__( "Set featured image for this Vector", "selskaberne" ),
		"remove_featured_image" => esc_html__( "Remove featured image for this Vector", "selskaberne" ),
		"use_featured_image" => esc_html__( "Use as featured image for this Vector", "selskaberne" ),
		"archives" => esc_html__( "Vector archives", "selskaberne" ),
		"insert_into_item" => esc_html__( "Insert into Vector", "selskaberne" ),
		"uploaded_to_this_item" => esc_html__( "Upload to this Vector", "selskaberne" ),
		"filter_items_list" => esc_html__( "Filter Vectors list", "selskaberne" ),
		"items_list_navigation" => esc_html__( "Vectors list navigation", "selskaberne" ),
		"items_list" => esc_html__( "Vectors list", "selskaberne" ),
		"attributes" => esc_html__( "Vectors attributes", "selskaberne" ),
		"name_admin_bar" => esc_html__( "Vector", "selskaberne" ),
		"item_published" => esc_html__( "Vector published", "selskaberne" ),
		"item_published_privately" => esc_html__( "Vector published privately.", "selskaberne" ),
		"item_reverted_to_draft" => esc_html__( "Vector reverted to draft.", "selskaberne" ),
		"item_trashed" => esc_html__( "Vector trashed.", "selskaberne" ),
		"item_scheduled" => esc_html__( "Vector scheduled", "selskaberne" ),
		"item_updated" => esc_html__( "Vector updated.", "selskaberne" ),
		"parent_item_colon" => esc_html__( "Parent Vector:", "selskaberne" ),
	];

	$args = [
		"label" => esc_html__( "Vectors", "selskaberne" ),
		"labels" => $labels,
		"description" => "",
		"public" => true,
		"publicly_queryable" => true,
		"show_ui" => true,
		"show_in_rest" => true,
		"rest_base" => "",
		"rest_controller_class" => "WP_REST_Posts_Controller",
		"rest_namespace" => "wp/v2",
		"has_archive" => false,
		"show_in_menu" => true,
		"show_in_nav_menus" => true,
		"delete_with_user" => false,
		"exclude_from_search" => false,
		"capability_type" => "post",
		"map_meta_cap" => true,
		"hierarchical" => false,
		"can_export" => false,
		"rewrite" => [ "slug" => "vector", "with_front" => true ],
		"query_var" => true,
		"menu_position" => 100,
		"menu_icon" => "dashicons-star-filled",
		"supports" => [ "title", "editor", "thumbnail", "custom-fields" ],
		"taxonomies" => [ "media_category" ],
		"show_in_graphql" => false,
	];

	register_post_type( "vector", $args );

	/**
	 * Post Type: Embeds.
	 */

	$labels = [
		"name" => esc_html__( "Embeds", "selskaberne" ),
		"singular_name" => esc_html__( "Embed", "selskaberne" ),
		"menu_name" => esc_html__( "Embeds", "selskaberne" ),
		"all_items" => esc_html__( "All Embeds", "selskaberne" ),
		"add_new" => esc_html__( "Add new", "selskaberne" ),
		"add_new_item" => esc_html__( "Add new Embed", "selskaberne" ),
		"edit_item" => esc_html__( "Edit Embed", "selskaberne" ),
		"new_item" => esc_html__( "New Embed", "selskaberne" ),
		"view_item" => esc_html__( "View Embed", "selskaberne" ),
		"view_items" => esc_html__( "View Embeds", "selskaberne" ),
		"search_items" => esc_html__( "Search Embeds", "selskaberne" ),
		"not_found" => esc_html__( "No Embeds found", "selskaberne" ),
		"not_found_in_trash" => esc_html__( "No Embeds found in trash", "selskaberne" ),
		"parent" => esc_html__( "Parent Embed:", "selskaberne" ),
		"featured_image" => esc_html__( "Featured image for this Embed", "selskaberne" ),
		"set_featured_image" => esc_html__( "Set featured image for this Embed", "selskaberne" ),
		"remove_featured_image" => esc_html__( "Remove featured image for this Embed", "selskaberne" ),
		"use_featured_image" => esc_html__( "Use as featured image for this Embed", "selskaberne" ),
		"archives" => esc_html__( "Embed archives", "selskaberne" ),
		"insert_into_item" => esc_html__( "Insert into Embed", "selskaberne" ),
		"uploaded_to_this_item" => esc_html__( "Upload to this Embed", "selskaberne" ),
		"filter_items_list" => esc_html__( "Filter Embeds list", "selskaberne" ),
		"items_list_navigation" => esc_html__( "Embeds list navigation", "selskaberne" ),
		"items_list" => esc_html__( "Embeds list", "selskaberne" ),
		"attributes" => esc_html__( "Embeds attributes", "selskaberne" ),
		"name_admin_bar" => esc_html__( "Embed", "selskaberne" ),
		"item_published" => esc_html__( "Embed published", "selskaberne" ),
		"item_published_privately" => esc_html__( "Embed published privately.", "selskaberne" ),
		"item_reverted_to_draft" => esc_html__( "Embed reverted to draft.", "selskaberne" ),
		"item_trashed" => esc_html__( "Embed trashed.", "selskaberne" ),
		"item_scheduled" => esc_html__( "Embed scheduled", "selskaberne" ),
		"item_updated" => esc_html__( "Embed updated.", "selskaberne" ),
		"parent_item_colon" => esc_html__( "Parent Embed:", "selskaberne" ),
	];

	$args = [
		"label" => esc_html__( "Embeds", "selskaberne" ),
		"labels" => $labels,
		"description" => "",
		"public" => true,
		"publicly_queryable" => true,
		"show_ui" => true,
		"show_in_rest" => true,
		"rest_base" => "",
		"rest_controller_class" => "WP_REST_Posts_Controller",
		"rest_namespace" => "wp/v2",
		"has_archive" => false,
		"show_in_menu" => true,
		"show_in_nav_menus" => true,
		"delete_with_user" => false,
		"exclude_from_search" => false,
		"capability_type" => "post",
		"map_meta_cap" => true,
		"hierarchical" => false,
		"can_export" => false,
		"rewrite" => [ "slug" => "embed", "with_front" => true ],
		"query_var" => true,
		"menu_position" => 100,
		"menu_icon" => "dashicons-embed-video",
		"supports" => [ "title", "editor", "thumbnail", "custom-fields" ],
		"taxonomies" => [ "media_category" ],
		"show_in_graphql" => false,
	];

	register_post_type( "embed", $args );
}

add_action( 'init', 'cptui_register_my_cpts' );
