<?php

declare(strict_types=1);

namespace AcColumnTemplate\Column;

use AC;
use AC\Setting\Config;
use AC\Setting\FormatterCollection;
use ACP;

class Column extends ACP\Column\BaseFactory
{

    public function get_label(): string
    {
        return __('COLUMN_LABEL', 'ac-column-template');
    }

    public function get_column_type(): string
    {
        // Identifier, pick a unique name. Single word, no spaces. Underscores allowed.
        return 'ac-COLUMN_NAME';
    }

    protected function get_formatters(Config $config): FormatterCollection
    {
        return new FormatterCollection([
            new AC\Value\Formatter\Meta(new AC\MetaType('post'), 'my_custom_field_key'),
        ]);

        // Example 2: Same as above but written in a custom Formatter class
        //                require_once __DIR__ . '/../Formatter/ExampleFormatter.php';
        //
        //                return new AC\Setting\FormatterCollection([
        //                    new ExampleFormatter(),
        //                ]);

        // Example 3: Show the Post Type and make it linkable by using Admin Columns Formatters
        //        return new FormatterCollection([
        //            new AC\Value\Formatter\Post\PostTitle(),
        //            new AC\Value\Formatter\Post\PostLink('edit_post'),
        //        ]);

    }

    /**
     * Editing Service. Used by inline- and bulk-editing to update column values directly from within the list table.
     * @link https://docs.admincolumns.com/article/27-how-to-use-inline-editing
     * @link https://docs.admincolumns.com/article/67-how-to-use-bulk-editing
     */
    protected function get_editing(Config $config): ?ACP\Editing\Service
    {
        /**
         * Example #1 - A custom editing service. Create your own input field and set how you want your data to be saved
         */
        return new Editing();

        /**
         * Example #2 - A `Text` input field for a custom field value
         * @see ACP\Editing\Service\Post\Meta This model stores the data as metadata
         * @see ACP\Editing\View\Text Type of input field
         */
        // return new ACP\Editing\Service\Post\Meta('my_custom_field_key', new ACP\Editing\View\Text());
    }

    protected function get_sorting(Config $config): ?ACP\Sorting\Model\QueryBindings
    {
        // TODO
        return null;

        return parent::get_sorting($config); // TODO: Change the autogenerated stub
    }

    // Omit if you want the default export which should be fine for most cases
    protected function get_export(Config $config): ?ACP\Export\Service
    {
        return new Export();
    }

}